default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chat_box_development

test:
  <<: *default
  database: chat_box_test

production:
  <<: *default
  database: chat_box_production
  username: chat_box
  password: <%= ENV['CHAT_BOX_DATABASE_PASSWORD'] %>
